<?php





/**
 * Implements hook_menu().
 */
function show_all_sites_menu()
{
    $items = array();
    $items['admin/config/show_all_sites'] = array(
        'title' => 'Administer Show All Sites',
        'description' => 'Configure settings for Show All Sites.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('show_all_sites_settings_form'),
        'access arguments' => array('admin_show_all_sites'),
        'file' => 'show_all_sites.admin.inc',
    );

    $items['admin/reports/show/subsites'] = array(
        'title'=>'Subsites At-a-Glance Report',
        'description'=>t('Shows all sites in /sites/ folder. Renders URL if configured properly. Also shows summation of all webforms.'),
        'page callback'=> 'show_all_sites_subsites_report_content',
        'access arguments'=>array('see_show_all_sites'),
        'file'=>'show_all_sites.report.inc',
    );


    $items['admin/reports/show/all/webforms/at/a/glance'] = array(
        'title'=>t('Webforms at-a-glance Report'),
        'description'=>t('Also shows summation of all webforms in an at-a-glance styled report.'),
        'page callback'=> 'show_all_sites_webforms_at_a_glance',
        'access arguments'=>array('see_show_all_sites'),
        'file'=>'show_all_sites.report.inc',
    );


    return $items;


}

/**
 * Implements hook_permission().
 */
function show_all_sites_permission()
{
    $permissions = array();
    $permissions['admin_show_all_sites'] = array(
        'title' => t('Administer'),
        'description' => t(''),
    );
    $permissions['see_show_all_sites'] = array(
        'title'=> t('Can see data from the block'),
        'description'=>t('Necessary to see any of the block content. This is a secondary measure to prevent block access. ')
    );

    return $permissions;
}
